my:
    okcoin:
        wsuri: wss://real.okcoin.cn:10440/websocket/okcoinapi
        cfg: okcoin
        sessionID: ?sessionID=FIX.4.4:f75dcc4d-13fa-4118-a908-050b530f6913->OKSERVER
        userName: f75dcc4d-13fa-4118-a908-050b530f6913
        password: MY_OKCOIN_PASSWORD